-- 0005_oauth.sql
-- OAuth login (issue #40): Google + GitHub sign-in alongside the existing
-- password auth (supplements it, never replaces it).
--
-- users.password_hash stays NOT NULL, unchanged. An earlier version of this
-- migration made it nullable via the standard SQLite table-rebuild pattern
-- (create the new shape, copy data, drop the old table, rename), with
-- PRAGMA foreign_keys toggled off/on around it -- this passed against the
-- local node:sqlite test shim (tests/backend/fakeD1.ts) but failed against
-- the real production D1 database with a FOREIGN KEY constraint error on
-- the DROP TABLE step: D1 does not honor PRAGMA foreign_keys = OFF across a
-- migration file the way a genuine local SQLite session does. Confirmed via
-- a real `wrangler d1 migrations apply --remote` attempt (rolled back
-- cleanly, no data lost, D1 applies each migration atomically). Rather than
-- fight that gap, OAuth-only accounts instead get a fixed sentinel string
-- in password_hash (see backend/src/utils/crypto.ts's
-- OAUTH_NO_PASSWORD_SENTINEL) -- it never matches the "pbkdf2$..." format
-- verifyPassword expects, so a password login attempt against such an
-- account fails exactly the same way a nullable column + null-check would,
-- with zero schema risk.
--
-- oauth_identities: links a provider account to a users row. A user can
-- have a password, one or more linked identities, or both -- never neither
-- (registration always creates exactly one path in).
--
-- oauth_states / oauth_exchange_codes: the Worker is stateless and
-- horizontally scaled, so the CSRF `state` generated by /oauth/:provider
-- /start must be persisted somewhere the later /callback request (quite
-- possibly a different Worker instance) can read it back -- same reason the
-- token handoff needs its own table. The frontend (GitHub Pages) and
-- backend (Workers) are different origins with no shared cookie, so the
-- callback (server-side, holds the client secret) can't set a cookie or
-- embed the JWT directly in the redirect URL (browser history/referrer
-- risk) -- instead it stores the already-issued JWT behind a short-lived,
-- single-use random code and redirects the browser to the frontend with
-- only that code; the frontend immediately exchanges it for the real JWT
-- via POST.
--
-- Never edit this file after it has been merged — every future schema
-- change is a new migration file (Technical Standards §3).

CREATE TABLE oauth_identities (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider TEXT NOT NULL, -- 'google' | 'github'
    provider_user_id TEXT NOT NULL, -- the provider's own stable subject/user id, never the email (emails can change)
    email TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (provider, provider_user_id)
);

CREATE INDEX idx_oauth_identities_user_id ON oauth_identities(user_id);

CREATE TABLE oauth_states (
    state TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    expires_at DATETIME NOT NULL
);

-- code_hash is SHA-256 of the actual code handed to the browser -- the raw
-- value is never stored, mirroring password_hash's own principle.
CREATE TABLE oauth_exchange_codes (
    code_hash TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at DATETIME NOT NULL,
    consumed_at DATETIME
);
