-- 0005_oauth.sql
-- OAuth login (issue #40): Google + GitHub sign-in alongside the existing
-- password auth (supplements it, never replaces it). Three changes:
--
--   1. users.password_hash becomes nullable -- an OAuth-only account has no
--      password at all. SQLite can't drop a column's NOT NULL constraint via
--      ALTER TABLE, so this rebuilds the table (the standard SQLite pattern
--      for constraint changes ALTER TABLE can't express: create the new
--      shape, copy the data, drop the old table, rename). PRAGMA
--      foreign_keys is toggled off/on around it since several tables
--      (user_settings, books, reading_progress, shelves/tags/favorites)
--      hold FKs to users(id) that would otherwise block dropping it
--      mid-rebuild -- SQLite resolves FK targets by table name, so they
--      keep working once the rebuilt table is renamed back to "users".
--
--   2. oauth_identities: links a provider account to a users row. A user can
--      have a password, one or more linked identities, or both -- never
--      neither (registration always creates exactly one path in).
--
--   3. oauth_states / oauth_exchange_codes: the Worker is stateless and
--      horizontally scaled, so the CSRF `state` generated by /oauth/:provider
--      /start must be persisted somewhere the later /callback request (quite
--      possibly a different Worker instance) can read it back -- same reason
--      the token handoff needs its own table. The frontend (GitHub Pages)
--      and backend (Workers) are different origins with no shared cookie, so
--      the callback (server-side, holds the client secret) can't set a
--      cookie or embed the JWT directly in the redirect URL (browser
--      history/referrer risk) -- instead it stores the already-issued JWT
--      behind a short-lived, single-use random code and redirects the
--      browser to the frontend with only that code; the frontend
--      immediately exchanges it for the real JWT via POST.
--
-- Never edit this file after it has been merged — every future schema
-- change is a new migration file (Technical Standards §3).

PRAGMA foreign_keys = OFF;

CREATE TABLE users_new (
    id INTEGER PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT,
    avatar_url TEXT,
    role_id INTEGER NOT NULL REFERENCES roles(id),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login DATETIME,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME
);

INSERT INTO users_new (id, username, email, password_hash, avatar_url, role_id, created_at, last_login, updated_at, deleted_at)
SELECT id, username, email, password_hash, avatar_url, role_id, created_at, last_login, updated_at, deleted_at FROM users;

DROP TABLE users;
ALTER TABLE users_new RENAME TO users;

CREATE INDEX idx_users_role_id ON users(role_id);

PRAGMA foreign_keys = ON;

CREATE TABLE oauth_identities (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider TEXT NOT NULL, -- 'google' | 'github'
    provider_user_id TEXT NOT NULL, -- the provider's own stable subject/user id, never the email (emails can change)
    email TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (provider, provider_user_id)
);

CREATE INDEX idx_oauth_identities_user_id ON oauth_identities(user_id);

CREATE TABLE oauth_states (
    state TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    expires_at DATETIME NOT NULL
);

-- code_hash is SHA-256 of the actual code handed to the browser -- the raw
-- value is never stored, mirroring password_hash's own principle.
CREATE TABLE oauth_exchange_codes (
    code_hash TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at DATETIME NOT NULL,
    consumed_at DATETIME
);
